# Generated by Django 2.1.5 on 2019-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
