# Generated by Django 2.1.5 on 2019-02-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190201_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttage',
            name='tage',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
